### ISSUE TITLE
QCA9984 beta - lede vs. standard

### ISSUE THREAD

**Issue by jerrytouille** [greearb/ath10k-ct#110]
**Description of the problem (how to configure, how to reproduce, how often it happens).**

QCA9984 beta - lede and standard use to be the same, _until the latest change on Dec. 13_:

...-community.bin (12/**19**/19): 10.4b-ct-9984-fH-012-**9035e8e87**
...-community-12.bin-lede.014 (12/**16**/19): 10.4b-ct-9984-fH-012-**6acc9b999**

(Link: https://www.candelatech.com/downloads/ath10k-9984-10-4b/)

**Comment by greearb** [comment]
I'll update the 'lede' builds eventually, the latest changes that are not offered to openwrt are just
debugging changes.  This is a normal thing and nothing to be worried about.
