### ISSUE TITLE
5 Ghz problem on QCA9886

### ISSUE THREAD

**Issue by julianocss** [greearb/ath10k-ct#118]
Hello @greearb.

First of all, I'm sorry if I'm reporting this problem in the wrong place (you can close it if so). 

Can you tell me if this problem can be solved with some correction of the CT driver? Or should I report this elsewhere?

https://github.com/openwrt/openwrt/pull/2470

Regards.
Juliano

**Comment by greearb** [comment]
I'm closing this.  Please open a new one if you have reason to believe it is a firmware problem, and not something else like bad board file or flaky hardware.
