### ISSUE TITLE
Issues with latest Candelatech firmware binaries files

### ISSUE THREAD

**Issue by julianocss** [greearb/ath10k-ct#158]
Hi @greearb.

There is a problem with the latest binaries files generated in Candelatech site.
My router is an  Arcer C60 V2, QCA9886.
The 5Ghz radio does not start with these files.

I tried to revert to "firmware-5-ct-htt-mgt-community-12.bin-lede.019 (downloaded now)" and also does not worked.
The only way to start 5Ghz radio again was replacing the firmware-5.bin file from my previous OpenWRT build.

I noticed that the current file size is very different.

Old (019): 555k
New (019): 477k

Dmesg is attached.

Regards,
Juliano

[dmesg_new.txt](https://github.com/greearb/ath10k-ct/files/5232673/dmesg_new.txt)
[dmesg_old.txt](https://github.com/greearb/ath10k-ct/files/5232671/dmesg_old.txt)

**Comment by greearb** [comment]
You are loading a 4019 firmware (see "firmware ver", please show me what link you got this from if the link is mentioning 9888, which is your chipset:

[   19.476215] ath10k_pci 0000:00:00.0: fwcfg key: dma_burst  val: 0
[   20.081905] ath10k_pci 0000:00:00.0: qca9888 hw2.0 target 0x01000000 chip_id 0x00000000 sub 0000:0000
[   20.091471] ath10k_pci 0000:00:00.0: kconfig debug 0 debugfs 1 tracing 0 dfs 1 testmode 0
[   20.108881] ath10k_pci 0000:00:00.0: firmware ver 10.4b-ct-4019-tH-13-6d73a309a api 5 features mfp,peer-flow-ctrl,txstatus-noack,wmi-10.x-CT,ratemask-CT,regdump-CT,txrate-CT,flush-all-CT,pingpong-CT,ch-regs-CT,nop-CT,htt-mgt-CT,set-special-CT,no-bmiss-CT,tx-rc-CT,cust-stats-CT,txrate2-CT,beacon-cb-CT,wmi-block-ack-CT,wmi-bcn-rc-CT crc32 42d142aa

**Comment by julianocss** [comment]
Hi @greearb .


[https://www.candelatech.com/downloads/ath10k-4019-10-4b/firmware-5-ct-full-htt-mgt-community-12.bin-lede.020
](url)

Regret:
https://www.candelatech.com/downloads/ath10k-4019-10-4b/firmware-5-ct-full-htt-mgt-community-12.bin-lede.019

Latest stable:

[ct-firmware-5.txt](https://github.com/greearb/ath10k-ct/files/5236110/ct-firmware-5.txt)

Juliano

**Comment by greearb** [comment]
You have a 9888 radio in that system, so in the firmware directory QCA9888/*/ you need to copy 9888 firmware, not the 4019 firmware you link above.  You may also have an ipq4019 radio  on your system, the firmware you link above would go into /lib/firmware/ath10k/QCA4019/*/

**Comment by julianocss** [comment]
Hi @greearb.

My mistake. sorry about that.
I will test the latest binaries.
Closing this issue.

Regards,
Juliano
