### ISSUE TITLE
Firmware is crashing on tp-link router

### ISSUE THREAD

**Issue by bttd** [greearb/ath10k-ct#183]
Please provide this info.  See this link for more info on how to gather debug
info:  http://www.candelatech.com/ath10k-bugs.php

**Description of the problem (how to configure, how to reproduce, how often it happens).**

Hi,

This problem happening 2 or 3 times a week. We using MacBooks connected to the router.
The firmware crashes sometimes, and every device loses the network connection until the wifi restarts. 

**Software (OS, Firmware version, kernel, driver, etc)**

Hostname | OpenWrt
Firmware Version | OpenWrt 21.02.0-rc1 r16046-59980f7aaf / LuCI openwrt-21.02 branch git-21.106.55967-06dd6b5
Kernel Version | 5.4.111

Same happened on stable OpenWrt (19.07.7)

**Hardware (NIC chipset, platform, etc)**

Model | TP-Link Archer C7 v5
Architecture | Qualcomm Atheros QCA956X ver 1 rev 0

**Logs (dmesg, maybe supplicant and/or hostap)**

https://pastebin.com/xVg5sa31

**Comment by greearb** [comment]
The firmware hung, which is unfortunately somewhat normal, and then driver forced restart:
[313384.521735] ath10k_pci 0000:00:00.0: Cannot communicate with firmware, previous wmi cmds: 36904:78270981 36954:78270754 36904:78270743 36954:78270721, jiffies: 78271552, attempting to fake crash and restart firmware, dev-flags: 0x42
[313384.543466] ath10k_pci 0000:00:00.0: failed to send wmi nop: -143
[313384.550012] ath10k_pci 0000:00:00.0: could not request stats (type -268435456 ret -143 specifier 1)

Did system recover automatically after this, or did you have to reboot it?

**Comment by bttd** [comment]
System recover automatically in few minutes

**Comment by clebersantz** [comment]
I have the same problem, with CT firmware sometime WIFI freezes and need to restart router to get it working again.
Using non CT firmware it doesn't occurs and I get faster speeds.

This happens with 2.4GHz, on a TP-Link Archer C7 v2 with OpenWRT 21.02, using ath10k-firmware-qca988x-ct and kmod-ath10k-ct.

There as lot of topics in openwrt about it even with others OpenWRT versions, but none solution. See https://forum.openwrt.org/t/archer-c7-2-4-ghz-wireless-dies-in-24-48-hours/.

there is a workaround that works for me as well, when running the command below the problem still occurs, but WIFI continue to work after that:
$ iw dev wlan_2g scan trigger freq 2462 flush

**Comment by greearb** [comment]
@clebersantz seems you have a different bug, your system does not actually recover with ath10k-ct driver/firmware (sometimes?)  If you can get dmesg output after a freeze (and that may require serial console), then I will see if I can notice anything interesting.  Please open a new bug if you want to pursue that.  And, what problem still occurs but is different when you do that scan trigger freq thing?  Closing this bug...plz add answers/comments to new bug.
