### ISSUE TITLE
Wrong kernel version with 5.15 source

### ISSUE THREAD

**Issue by Ansuel** [greearb/ath10k-ct#191]
@greearb We are testing 5.15 source on openwrt and we just notice that in the log it does still report 5.12.
https://github.com/greearb/ath10k-ct/blob/3d3450c55b983c22753a0f7ff197ec1525140348/ath10k-5.15/pci.c#L3877

Worth upgrading to prevent some confusion?

**Comment by greearb** [comment]
ommit e8e166fee23226e5d495afbdb7ed681d747d115b (HEAD -> master, origin/master)
Author: Ben Greear <greearb@candelatech.com>
Date:   Sun Nov 21 08:54:00 2021 -0800

    ath10k-ct:  Fix kernel version string.
    
    Signed-off-by: Ben Greear <greearb@candelatech.com>
