### ISSUE TITLE
High ping and lost packets on CT firmwares

### ISSUE THREAD

**Issue by master8282** [greearb/ath10k-ct#24]
Dear Ben,

System:
kernel:
$ uname -a
Linux ubuntu1804 4.16.15 #2 SMP Tue Jun 19 16:42:09 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux

drivers:
ath10k-ct for 4.16

$ hostapd -v
hostapd v2.7-devel-hostap_2_3-5889-g91b1c5482
User space daemon for IEEE 802.11 AP management,
IEEE 802.1X/WPA/WPA2/EAP/RADIUS Authenticator
Copyright (c) 2002-2017, Jouni Malinen <j@w1.fi> and contributors
It was built by hostapd-ct.

Hardware:
WLE1216V5-20

02:00.0 Network controller: Qualcomm Atheros Device 0046
	Subsystem: Qualcomm Atheros Device cafe
	Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
	Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Latency: 0, Cache Line Size: 64 bytes
	Interrupt: pin A routed to IRQ 49
	Region 0: Memory at f7c00000 (64-bit, non-prefetchable) [size=2M]
	Capabilities: <access denied>
	Kernel driver in use: ath10k_pci
	Kernel modules: ath10k_pci

Using CT firmwares (now I show example for https://www.candelatech.com/downloads/ath10k-9984-10-4/ath10k-fw-beta/firmware-5-ct-community.bin) I got the following issue:
I see it as 160Mhz as 80Mhz and 40Mhz too.

When I ping AP/gateway I see normal ping:

ant@ubuntu:~$ ping 192.168.111.1
PING 192.168.111.1 (192.168.111.1) 56(84) bytes of data.
64 bytes from 192.168.111.1: icmp_seq=1 ttl=64 time=1.73 ms
64 bytes from 192.168.111.1: icmp_seq=2 ttl=64 time=1.43 ms
64 bytes from 192.168.111.1: icmp_seq=3 ttl=64 time=1.79 ms
64 bytes from 192.168.111.1: icmp_seq=4 ttl=64 time=2.38 ms
64 bytes from 192.168.111.1: icmp_seq=5 ttl=64 time=1.76 ms
64 bytes from 192.168.111.1: icmp_seq=6 ttl=64 time=2.03 ms
64 bytes from 192.168.111.1: icmp_seq=7 ttl=64 time=1.48 ms
64 bytes from 192.168.111.1: icmp_seq=8 ttl=64 time=1.67 ms
64 bytes from 192.168.111.1: icmp_seq=9 ttl=64 time=2.19 ms
64 bytes from 192.168.111.1: icmp_seq=10 ttl=64 time=1.70 ms
^C
--- 192.168.111.1 ping statistics ---
10 packets transmitted, 10 received, 0% packet loss, time 9015ms
rtt min/avg/max/mdev = 1.431/1.819/2.384/0.286 ms

Perfect result, no qustions.

But when I try to ping clients I see the following:

ant@ubuntu1804:~$ ping 192.168.111.109
PING 192.168.111.109 (192.168.111.109) 56(84) bytes of data.
64 bytes from 192.168.111.109: icmp_seq=5 ttl=64 time=4204 ms
64 bytes from 192.168.111.109: icmp_seq=6 ttl=64 time=3181 ms
64 bytes from 192.168.111.109: icmp_seq=7 ttl=64 time=2158 ms
64 bytes from 192.168.111.109: icmp_seq=8 ttl=64 time=1135 ms
64 bytes from 192.168.111.109: icmp_seq=9 ttl=64 time=111 ms
^C
--- 192.168.111.109 ping statistics ---
12 packets transmitted, 5 received, 58% packet loss, time 11224ms
rtt min/avg/max/mdev = 111.944/2158.601/4204.962/1447.053 ms, pipe 5

ant@ubuntu1804:~$ ping 192.168.111.84
PING 192.168.111.84 (192.168.111.84) 56(84) bytes of data.
64 bytes from 192.168.111.84: icmp_seq=1 ttl=64 time=3766 ms
64 bytes from 192.168.111.84: icmp_seq=2 ttl=64 time=2743 ms
64 bytes from 192.168.111.84: icmp_seq=3 ttl=64 time=1719 ms
64 bytes from 192.168.111.84: icmp_seq=4 ttl=64 time=695 ms
64 bytes from 192.168.111.84: icmp_seq=5 ttl=64 time=4700 ms
64 bytes from 192.168.111.84: icmp_seq=6 ttl=64 time=3683 ms
64 bytes from 192.168.111.84: icmp_seq=7 ttl=64 time=2660 ms
64 bytes from 192.168.111.84: icmp_seq=8 ttl=64 time=1637 ms
64 bytes from 192.168.111.84: icmp_seq=9 ttl=64 time=613 ms
^C
--- 192.168.111.84 ping statistics ---
11 packets transmitted, 9 received, 18% packet loss, time 10175ms
rtt min/avg/max/mdev = 613.488/2469.065/4700.211/1337.073 ms, pipe 5

Ping is very high and many packets were lost.

Here are some outputs from the AP:

ant@ubuntu1804:~$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether c0:3f:d5:6f:aa:5f brd ff:ff:ff:ff:ff:ff
    inet 172.19.12.63/24 brd 172.19.12.255 scope global eno1
       valid_lft forever preferred_lft forever
    inet6 fe80::c23f:d5ff:fe6f:aa5f/64 scope link 
       valid_lft forever preferred_lft forever
3: wlp2s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br0 state UP group default qlen 1000
    link/ether 04:f0:21:38:98:ae brd ff:ff:ff:ff:ff:ff
4: br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 04:f0:21:38:98:ae brd ff:ff:ff:ff:ff:ff
    inet 192.168.111.1/24 brd 192.168.111.255 scope global br0
       valid_lft forever preferred_lft forever
    inet6 fe80::f4ad:8eff:fe87:f88f/64 scope link 
       valid_lft forever preferred_lft forever

ant@ubuntu1804:~$ ip r
default via 172.19.12.1 dev eno1 
172.19.12.0/24 dev eno1 proto kernel scope link src 172.19.12.63 
192.168.111.0/24 dev br0 proto kernel scope link src 192.168.111.1 

ant@ubuntu1804:~$ brctl show
bridge name	bridge id		STP enabled	interfaces
br0		8000.04f0213898ae	no		wlp2s0

ant@ubuntu1804:~$ arp
Address                  HWtype  HWaddress           Flags Mask            Iface
172.19.12.128                    (incomplete)                              eno1
192.168.111.84           ether   5c:51:88:57:7d:94   C                     br0
192.168.111.109          ether   0c:8b:fd:07:f2:ab   C                     br0
172.19.12.25             ether   00:90:f5:ec:55:5d   C                     eno1
172.19.12.1              ether   04:6c:9d:22:c9:cc   C                     eno1

Power manager is off:
ant@ubuntu1804:~$ iwconfig wlp2s0
wlp2s0    IEEE 802.11  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=23 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:off

tcpdump captures on both sides:

ant@ubuntu1804:~$ ping 192.168.111.109
PING 192.168.111.109 (192.168.111.109) 56(84) bytes of data.
64 bytes from 192.168.111.109: icmp_seq=1 ttl=64 time=4976 ms
64 bytes from 192.168.111.109: icmp_seq=2 ttl=64 time=3963 ms
64 bytes from 192.168.111.109: icmp_seq=3 ttl=64 time=2939 ms
64 bytes from 192.168.111.109: icmp_seq=4 ttl=64 time=1915 ms
64 bytes from 192.168.111.109: icmp_seq=5 ttl=64 time=892 ms
^C
--- 192.168.111.109 ping statistics ---
8 packets transmitted, 5 received, 37% packet loss, time 7126ms
rtt min/avg/max/mdev = 892.231/2937.520/4976.543/1444.754 ms, pipe 5

root@ubuntu1804:~# tcpdump -lei wlp2s0 -vv  icmp
tcpdump: listening on wlp2s0, link-type EN10MB (Ethernet), capture size 262144 bytes
16:03:34.992521 04:f0:21:38:98:ae (oui Unknown) > 0c:8b:fd:07:f2:ab (oui Unknown), ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 64, id 43984, offset 0, flags [DF], proto ICMP (1), length 84)
    192.168.111.1 > 192.168.111.109: ICMP echo request, id 1094, seq 1, length 64
16:03:36.006608 04:f0:21:38:98:ae (oui Unknown) > 0c:8b:fd:07:f2:ab (oui Unknown), ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 64, id 44059, offset 0, flags [DF], proto ICMP (1), length 84)
    192.168.111.1 > 192.168.111.109: ICMP echo request, id 1094, seq 2, length 64
16:03:37.030586 04:f0:21:38:98:ae (oui Unknown) > 0c:8b:fd:07:f2:ab (oui Unknown), ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 64, id 44176, offset 0, flags [DF], proto ICMP (1), length 84)
    192.168.111.1 > 192.168.111.109: ICMP echo request, id 1094, seq 3, length 64
16:03:38.054593 04:f0:21:38:98:ae (oui Unknown) > 0c:8b:fd:07:f2:ab (oui Unknown), ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 64, id 44303, offset 0, flags [DF], proto ICMP (1), length 84)
    192.168.111.1 > 192.168.111.109: ICMP echo request, id 1094, seq 4, length 64
16:03:39.078616 04:f0:21:38:98:ae (oui Unknown) > 0c:8b:fd:07:f2:ab (oui Unknown), ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 64, id 44461, offset 0, flags [DF], proto ICMP (1), length 84)
    192.168.111.1 > 192.168.111.109: ICMP echo request, id 1094, seq 5, length 64
16:03:39.969013 0c:8b:fd:07:f2:ab (oui Unknown) > 04:f0:21:38:98:ae (oui Unknown), ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 64, id 57452, offset 0, flags [none], proto ICMP (1), length 84)
    192.168.111.109 > 192.168.111.1: ICMP echo reply, id 1094, seq 1, length 64
16:03:39.969819 0c:8b:fd:07:f2:ab (oui Unknown) > 04:f0:21:38:98:ae (oui Unknown), ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 64, id 57453, offset 0, flags [none], proto ICMP (1), length 84)
    192.168.111.109 > 192.168.111.1: ICMP echo reply, id 1094, seq 2, length 64
16:03:39.970138 0c:8b:fd:07:f2:ab (oui Unknown) > 04:f0:21:38:98:ae (oui Unknown), ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 64, id 57454, offset 0, flags [none], proto ICMP (1), length 84)
    192.168.111.109 > 192.168.111.1: ICMP echo reply, id 1094, seq 3, length 64
16:03:39.970500 0c:8b:fd:07:f2:ab (oui Unknown) > 04:f0:21:38:98:ae (oui Unknown), ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 64, id 57455, offset 0, flags [none], proto ICMP (1), length 84)
    192.168.111.109 > 192.168.111.1: ICMP echo reply, id 1094, seq 4, length 64
16:03:39.970794 0c:8b:fd:07:f2:ab (oui Unknown) > 04:f0:21:38:98:ae (oui Unknown), ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 64, id 57456, offset 0, flags [none], proto ICMP (1), length 84)
    192.168.111.109 > 192.168.111.1: ICMP echo reply, id 1094, seq 5, length 64
16:03:40.079157 04:f0:21:38:98:ae (oui Unknown) > 0c:8b:fd:07:f2:ab (oui Unknown), ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 64, id 44471, offset 0, flags [DF], proto ICMP (1), length 84)
    192.168.111.1 > 192.168.111.109: ICMP echo request, id 1094, seq 6, length 64
16:03:41.094597 04:f0:21:38:98:ae (oui Unknown) > 0c:8b:fd:07:f2:ab (oui Unknown), ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 64, id 44606, offset 0, flags [DF], proto ICMP (1), length 84)
    192.168.111.1 > 192.168.111.109: ICMP echo request, id 1094, seq 7, length 64
16:03:42.118589 04:f0:21:38:98:ae (oui Unknown) > 0c:8b:fd:07:f2:ab (oui Unknown), ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 64, id 44747, offset 0, flags [DF], proto ICMP (1), length 84)
    192.168.111.1 > 192.168.111.109: ICMP echo request, id 1094, seq 8, length 64
16:03:45.049755 0c:8b:fd:07:f2:ab (oui Unknown) > 04:f0:21:38:98:ae (oui Unknown), ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 64, id 57694, offset 0, flags [none], proto ICMP (1), length 84)
    192.168.111.109 > 192.168.111.1: ICMP echo reply, id 1094, seq 8, length 64

root@ubuntu:~# tcpdump -lei wlp3s0 -vv icmp
tcpdump: listening on wlp3s0, link-type EN10MB (Ethernet), capture size 262144 bytes
16:03:39.976216 04:f0:21:38:98:ae (oui Unknown) > 0c:8b:fd:07:f2:ab (oui Unknown), ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 64, id 43984, offset 0, flags [DF], proto ICMP (1), length 84)
    _gateway > ubuntu: ICMP echo request, id 1094, seq 1, length 64
16:03:39.976294 0c:8b:fd:07:f2:ab (oui Unknown) > 04:f0:21:38:98:ae (oui Unknown), ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 64, id 57452, offset 0, flags [none], proto ICMP (1), length 84)
    ubuntu > _gateway: ICMP echo reply, id 1094, seq 1, length 64
16:03:39.976322 04:f0:21:38:98:ae (oui Unknown) > 0c:8b:fd:07:f2:ab (oui Unknown), ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 64, id 44059, offset 0, flags [DF], proto ICMP (1), length 84)
    _gateway > ubuntu: ICMP echo request, id 1094, seq 2, length 64
16:03:39.976346 0c:8b:fd:07:f2:ab (oui Unknown) > 04:f0:21:38:98:ae (oui Unknown), ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 64, id 57453, offset 0, flags [none], proto ICMP (1), length 84)
    ubuntu > _gateway: ICMP echo reply, id 1094, seq 2, length 64
16:03:39.976358 04:f0:21:38:98:ae (oui Unknown) > 0c:8b:fd:07:f2:ab (oui Unknown), ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 64, id 44176, offset 0, flags [DF], proto ICMP (1), length 84)
    _gateway > ubuntu: ICMP echo request, id 1094, seq 3, length 64
16:03:39.976378 0c:8b:fd:07:f2:ab (oui Unknown) > 04:f0:21:38:98:ae (oui Unknown), ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 64, id 57454, offset 0, flags [none], proto ICMP (1), length 84)
    ubuntu > _gateway: ICMP echo reply, id 1094, seq 3, length 64
16:03:39.976400 04:f0:21:38:98:ae (oui Unknown) > 0c:8b:fd:07:f2:ab (oui Unknown), ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 64, id 44303, offset 0, flags [DF], proto ICMP (1), length 84)
    _gateway > ubuntu: ICMP echo request, id 1094, seq 4, length 64
16:03:45.056687 04:f0:21:38:98:ae (oui Unknown) > 0c:8b:fd:07:f2:ab (oui Unknown), ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 64, id 44747, offset 0, flags [DF], proto ICMP (1), length 84)
    _gateway > ubuntu: ICMP echo request, id 1094, seq 8, length 64
16:03:45.056721 0c:8b:fd:07:f2:ab (oui Unknown) > 04:f0:21:38:98:ae (oui Unknown), ethertype IPv4 (0x0800), length 98: (tos 0x0, ttl 64, id 57694, offset 0, flags [none], proto ICMP (1), length 84)
    ubuntu > _gateway: ICMP echo reply, id 1094, seq 8, length 64

tracepath:
ant@ubuntu1804:~$ tracepath 192.168.111.109
 1?: [LOCALHOST]                      pmtu 1500
 1:  no reply
 2:  no reply
 2:  192.168.111.109                                     3040.946ms reached
     Resume: pmtu 1500 hops 2 back 1 

I noticed that using kernel's native firmware-5.bit I don't see the issue as with ath10-ct as original ath10k modules with any hostapd(original and hostapd-ct), looks like the issue in firmware-5.bin from Candella Technology only.

Thank you,
Alex.

**Comment by greearb** [comment]
I have ported my patches forward and rebased on a newer qca firmware.  For another bug, I did a build for each commit.  You can use this to bisect the commits to see where the bug was introduced.  First, test the first and last build to make sure that the first works.  If the last fails, then you can bisect.  If the last works, then let me know...the rebase to newer code might have fixed it.

https://www.candelatech.com/downloads/ath10k-9984-10-4b/ath10k-fw-beta/all_builds-9984b-full-community-5-862.tar.gz

**Comment by greearb** [comment]
Please try the latest firmware...it is attached.  Let me know if problems persist.

[firmware-5-full-htt-mgt-community.bin.gz](https://github.com/greearb/ath10k-ct/files/2692062/firmware-5-full-htt-mgt-community.bin.gz)

**Comment by greearb** [comment]
Lots has changed since this bug.  Please try latest firmware and if problems still persist, please open a new bug.
