### ISSUE TITLE
archer-c7-v2, qca9880, AP mode, SWBA overrun on iperf test.

### ISSUE THREAD

**Issue by slthomason** [greearb/ath10k-ct#4]
Archer C7 v2 - AR71xx 

Driver commit: 956e2609b7e42c8c710bba10ef925a5be1be5137

On this firmware:
[   15.050375] ath10k_pci 0000:01:00.0: firmware ver 10.1-ct-8x-__fW-019-6375cb7 api 2 features wmi-10.x,has-wmi-mgmt-tx,txstatus-noack,wmi-10.x-CT,ratemask-CT crc32 10d5163b

User reports problems when downloading via iperf on the 2Ghz radio (which is ath9k),
but it seems ath10k is spitting the errors below.  When ath10k radio is disabled, test runs
OK.  Maye there is some interference between the two radios?

We got this:
Mon Jun 19 10:42:51 2017 kern.warn kernel: [  635.132430] ath10k_pci 0000:01:00.0: htt peer map vdev 0 peer ec:08:6b:f9:74:7d id 419
Mon Jun 19 10:42:52 2017 daemon.info hostapd: wlan1: STA 20:16:d8:bd:f5:83 WPA: group key handshake completed (RSN)
Mon Jun 19 10:42:52 2017 daemon.info hostapd: wlan1: STA b0:c5:54:19:fb:df WPA: group key handshake completed (RSN)
Mon Jun 19 10:42:52 2017 daemon.info hostapd: wlan1: STA e0:66:78:27:4d:72 WPA: group key handshake completed (RSN)
Mon Jun 19 10:42:52 2017 daemon.info hostapd: wlan1: STA 4c:66:41:9c:0f:8e WPA: group key handshake completed (RSN)
Mon Jun 19 10:42:55 2017 daemon.info hostapd: wlan1: STA e0:66:78:19:31:5d IEEE 802.11: authenticated
Mon Jun 19 10:42:55 2017 daemon.info hostapd: wlan1: STA e0:66:78:19:31:5d IEEE 802.11: associated (aid 5)
Mon Jun 19 10:42:55 2017 daemon.notice hostapd: wlan1: AP-STA-CONNECTED e0:66:78:19:31:5d
Mon Jun 19 10:42:55 2017 daemon.info hostapd: wlan1: STA e0:66:78:19:31:5d RADIUS: starting accounting session 81674F3F9239404A
Mon Jun 19 10:42:55 2017 daemon.info hostapd: wlan1: STA e0:66:78:19:31:5d WPA: pairwise key handshake completed (RSN)
Mon Jun 19 10:42:55 2017 daemon.info dnsmasq-dhcp[1672]: DHCPREQUEST(br-lan) 192.168.2.5 e0:66:78:19:31:5d
Mon Jun 19 10:42:55 2017 daemon.info dnsmasq-dhcp[1672]: DHCPACK(br-lan) 192.168.2.5 e0:66:78:19:31:5d Caryns-iPad
Mon Jun 19 10:47:07 2017 kern.warn kernel: [  887.408156] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:47:32 2017 kern.warn kernel: [  894.016329] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:47:52 2017 kern.warn kernel: [  894.023804] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:47:52 2017 kern.warn kernel: [  894.555731] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:47:52 2017 kern.warn kernel: [  894.563205] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:47:52 2017 kern.warn kernel: [  894.570644] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:47:52 2017 kern.warn kernel: [  896.039231] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:47:52 2017 kern.warn kernel: [  902.210334] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:47:52 2017 kern.warn kernel: [  903.411095] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:47:52 2017 kern.warn kernel: [  911.037291] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:47:52 2017 kern.warn kernel: [  911.436323] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:47:52 2017 kern.warn kernel: [  911.443829] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:47:52 2017 kern.warn kernel: [  916.143585] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:47:52 2017 kern.warn kernel: [  916.151054] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:47:52 2017 kern.warn kernel: [  916.513572] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:47:52 2017 kern.warn kernel: [  916.521042] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:47:52 2017 kern.warn kernel: [  917.058136] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:47:52 2017 kern.warn kernel: [  917.065572] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:47:52 2017 kern.warn kernel: [  917.365014] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:47:52 2017 kern.warn kernel: [  918.554659] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:47:52 2017 kern.warn kernel: [  928.775235] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:47:52 2017 kern.warn kernel: [  929.137677] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:47:52 2017 kern.warn kernel: [  929.612764] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:47:53 2017 kern.warn kernel: [  935.994486] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:47:53 2017 kern.warn kernel: [  936.001966] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:47:53 2017 kern.warn kernel: [  936.397429] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:47:53 2017 kern.warn kernel: [  936.404895] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:47:53 2017 daemon.notice hostapd: nl80211: nl80211_recv_beacons->nl_recvmsgs failed: -5
Mon Jun 19 10:47:53 2017 daemon.notice hostapd: nl80211: wpa_driver_nl80211_event_receive->nl_recvmsgs failed: -5
Mon Jun 19 10:47:53 2017 daemon.notice hostapd: wlan1: STA 34:a3:95:00:a8:6e IEEE 802.11: did not acknowledge authentication response
Mon Jun 19 10:47:53 2017 daemon.notice hostapd: wlan1: STA 34:a3:95:00:a8:6e IEEE 802.11: did not acknowledge authentication response
Mon Jun 19 10:47:53 2017 daemon.notice hostapd: wlan1: STA 34:a3:95:00:a8:6e IEEE 802.11: did not acknowledge authentication response
Mon Jun 19 10:47:53 2017 daemon.notice hostapd: wlan1: STA 34:a3:95:00:a8:6e IEEE 802.11: did not acknowledge authentication response
Mon Jun 19 10:47:53 2017 daemon.notice hostapd: wlan1: STA 34:a3:95:00:a8:6e IEEE 802.11: did not acknowledge authentication response
Mon Jun 19 10:48:09 2017 kern.warn kernel: [  952.669842] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:09 2017 kern.warn kernel: [  952.677269] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:09 2017 kern.warn kernel: [  952.684740] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:10 2017 kern.warn kernel: [  953.255552] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:10 2017 kern.warn kernel: [  953.263029] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:10 2017 kern.warn kernel: [  953.651328] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:10 2017 kern.warn kernel: [  953.658802] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:51 2017 kern.warn kernel: [  963.463492] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  969.131534] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  971.165135] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  973.947326] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  977.036276] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  979.639102] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  979.646532] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  979.654000] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  979.661438] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  979.668873] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  980.226541] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  980.234021] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  980.803839] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  980.811314] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  980.818759] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  980.826213] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  981.393024] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  981.400494] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  981.907268] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  981.914697] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  981.922152] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  982.399783] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  982.999097] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  983.006530] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  983.013998] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  983.021436] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  983.624037] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  983.631511] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  983.638954] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  984.245526] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  984.252998] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  984.260444] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  984.267881] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  984.879922] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  984.887394] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  985.415664] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  985.423140] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  985.430577] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  985.438019] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  986.004513] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  986.511967] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  986.519442] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  986.526861] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  986.944391] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  987.294581] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  987.909490] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  992.060583] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:52 2017 kern.warn kernel: [  993.107718] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
Mon Jun 19 10:48:58 2017 kern.warn kernel: [  997.737405] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon

Then using this firmware:
http://www.candelatech.com/downloads/ath10k-fw-beta/firmware-2-ct-full-htt-mgt-community.bin
We got this:
843.647815] device wlan1 left promiscuous mode
[  843.652485] br-lan: port 2(wlan1) entered disabled state
[  843.665871] device wlan0 left promiscuous mode
[  843.670461] br-lan: port 3(wlan0) entered disabled state
[  843.707720] ath10k_pci 0000:01:00.0: removing peer, htt peer unmap vdev 0 peer d8:fc:93:e4:30:18 id 80
[  843.718719] ath10k_pci 0000:01:00.0: removing peer, htt peer unmap vdev 0 peer 98:de:d0:68:11:bb id 341
[  843.728725] ath10k_pci 0000:01:00.0: removing peer, htt peer unmap vdev 0 peer 98:de:d0:68:11:bb id 421
[  843.738303] ath10k_pci 0000:01:00.0: removing peer, htt peer unmap vdev 0 peer 98:de:d0:68:11:bb id 389
[  843.747847] ath10k_pci 0000:01:00.0: removing peer, htt peer unmap vdev 0 peer 98:de:d0:68:11:bb id 485
[  844.849245] IPv6: ADDRCONF(NETDEV_UP): wlan1: link is not ready
[  845.966636] ath10k_pci 0000:01:00.0: 10.1 wmi init: vdevs: 16  peers: 127  tid: 256
[  845.983415] ath10k_pci 0000:01:00.0: wmi print 'P 128 V 8 T 410'
[  845.983466] ath10k_pci 0000:01:00.0: wmi print 'msdu-desc: 1424  sw-crypt: 0'
[  845.984008] ath10k_pci 0000:01:00.0: wmi print 'alloc rem: 25928 iram: 25808'
[  846.047174] ath10k_pci 0000:01:00.0: htt peer map vdev 0 peer 98:de:d0:68:11:bb id 341
[  846.055237] ath10k_pci 0000:01:00.0: htt peer map vdev 0 peer 98:de:d0:68:11:bb id 421
[  846.065009] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[  846.071602] device wlan1 entered promiscuous mode
[  846.084784] device wlan0 entered promiscuous mode
[  846.773273] ath10k_pci 0000:01:00.0: htt peer map vdev 0 peer 98:de:d0:68:11:bb id 389
[  846.781477] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[  846.788084] br-lan: port 3(wlan0) entered forwarding state
[  846.793717] br-lan: port 3(wlan0) entered forwarding state
[  846.845210] IPv6: ADDRCONF(NETDEV_CHANGE): wlan1: link becomes ready
[  846.851954] br-lan: port 2(wlan1) entered forwarding state
[  846.857571] br-lan: port 2(wlan1) entered forwarding state
[  847.911676] ath10k_pci 0000:01:00.0: htt peer map vdev 0 peer d8:fc:93:e4:30:18 id 80
[  847.923312] ath10k_pci 0000:01:00.0: band: 1  ratemask: 0xffffffff  hw-nss: 3 dev-id: 0x3c
[  848.791860] br-lan: port 3(wlan0) entered forwarding state
[  848.851855] br-lan: port 2(wlan1) entered forwarding state
[  890.248966] ath10k_pci 0000:01:00.0: removing peer, htt peer unmap vdev 0 peer d8:fc:93:e4:30:18 id 80
[ 1060.635120] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
[ 1061.947425] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
[ 1087.897587] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
[ 1088.218735] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
[ 1143.217426] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
[ 1234.430582] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
[ 1235.173593] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
[ 1371.397525] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
[ 1447.636065] ath10k_pci 0000:01:00.0: htt peer map vdev 0 peer 98:de:d0:68:11:bb id 485
[ 1449.948589] nf_conntrack: automatic helper assignment is deprecated and it will be removed soon. Use the iptables CT target to attach helpers instead.
[ 1534.462357] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
[ 1534.469839] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
[ 1534.477354] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
[ 1619.778477] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
[ 1620.025614] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
[ 1624.942850] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
[ 1627.119168] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
[ 1675.034619] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
[ 1720.782013] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
[ 1721.438926] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
[ 1721.809215] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
[ 1767.992163] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
[ 1812.076470] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
[ 1812.435222] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon

**Comment by greearb** [comment]
I believed this was fixed by the user upgrading to a newer LEDE release.  Please re-open if problem persists.

**Comment by slthomason** [comment]
We have spent the last week trying to figure out what reproduces this.  Today we were finally able to narrow it down.

We only get these errors when 2Ghz is under load (we replicate it doing an iperf test connected to the 2Ghz).  Running the CPU up to 100% does not cause this behavior, but when we run certain systems of ours that call heavily into the kernel - anytime the kworker starts to get even the least bit burdened (over 30% CPU), while doing an iperf test connected to the 2Ghz channel, we get the ath10k errors.

Further, the odd thing is that these errors are on the 5Ghz code (ath10k), however, we only replicate this when connected to the 2Ghz band (ath9k).  When we connect to the 5Ghz and put load from our systems and the iperf - it handles it fine.  However, when we go back to putting load from our system + iperf on the 2Ghz band, we get the below errors.

We have seen this with any system that puts load on kernel calls - not just our systems.  When the kworker gets at all burdened - this happens.

We have now confirmed this on the following build combinations:
LEDE 17.01 + ath10k (non-ct)
LEDE 17.01.2 + very latest ath10k-ct
LEDE 17.01.2 + ath10k (non-ct)
many, many other combinations

A couple of questions:
1) Where are these calls getting generated from?  
2) What is the actual problem happening here?
3) We are connected to the 2Ghz (ath9k).  Why is the code erroring in the the ath10k code?

kern.warn kernel: [ 1482.891420] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
kern.warn kernel: [ 1487.252602] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
kern.warn kernel: [ 1487.556625] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon

**Comment by BrianLian** [comment]
I have a same problem.
Any one find out what happan?

**Comment by blackyx81** [comment]
Device: D-Link DIR-869 (2,4GHz and 5GHz active)
LEDE 17.01.4

Same problem here:
[ 6585.271882] ath10k_pci 0000:00:00.0: SWBA overrun on vdev 0, skipped old beacon
[ 6586.587435] ath10k_pci 0000:00:00.0: SWBA overrun on vdev 0, skipped old beacon
...

After kernel warning the device freezes for a while, after 10 seconds the device responds normal.

Can someone clarify why this happens?

**Comment by Catfriend1** [comment]
Having those too:

```
[1193818.182719] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 2, skipped old beacon
[1193818.190325] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
[1212675.045773] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 2, skipped old beacon
[1212675.053382] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 0, skipped old beacon
[1227045.561476] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 1, skipped old beacon
[1227045.569089] ath10k_pci 0000:01:00.0: SWBA overrun on vdev 2, skipped old beacon
```

Will also try the solution from #87

**Comment by titiviking** [comment]
Same problem on my side:

`[314041.061508] ath10k_pci 0000:00:00.0: SWBA overrun on vdev 0, skipped old beacon
[314041.069122] ath10k_pci 0000:00:00.0: SWBA overrun on vdev 0, skipped old beacon
[314041.076715] ath10k_pci 0000:00:00.0: SWBA overrun on vdev 0, skipped old beacon
[314041.084296] ath10k_pci 0000:00:00.0: SWBA overrun on vdev 0, skipped old beacon
[314041.091896] ath10k_pci 0000:00:00.0: SWBA overrun on vdev 0, skipped old beacon
[314041.099477] ath10k_pci 0000:00:00.0: SWBA overrun on vdev 0, skipped old beacon
[314041.107067] ath10k_pci 0000:00:00.0: SWBA overrun on vdev 0, skipped old beacon
[314041.114650] ath10k_pci 0000:00:00.0: SWBA overrun on vdev 0, skipped old beacon
[314041.122233] ath10k_pci 0000:00:00.0: SWBA overrun on vdev 0, skipped old beacon
[314041.129781] ath10k_pci 0000:00:00.0: SWBA overrun on vdev 0, skipped old beacon
[314041.137353] ath10k_pci 0000:00:00.0: SWBA overrun on vdev 0, skipped old beacon
[314041.144942] ath10k_pci 0000:00:00.0: SWBA overrun on vdev 0, skipped old beacon
[314041.152526] ath10k_pci 0000:00:00.0: SWBA overrun on vdev 0, skipped old beacon
[314041.160100] ath10k_pci 0000:00:00.0: SWBA overrun on vdev 0, skipped old beacon
[314041.167669] ath10k_pci 0000:00:00.0: SWBA overrun on vdev 0, skipped old beacon`

Any working solution yet? 
I'm currently running OpenWRT 21.02

**Comment by klukonin** [comment]
Well, it's not a good approach to use patches from #87.
Those patches are for old kernel and current kernel should already has all patched parameters.

Please try to use htt firmware
https://openwrt.org/packages/pkgdata_owrt18_6/ath10k-firmware-qca988x-ct-htt
