### ISSUE TITLE
TX frame capture in monitor mode

### ISSUE THREAD

**Issue by jhaakana** [greearb/ath10k-ct#59]
- HW: Compex WLE1216V5-20 (QCA9984)
- Firmware: firmware ver 10.4-ct-9984-fW-011-cfc3436 (beta)
- board-2.bin: stock board-2.bin 
- OS: LEDE latest, mvebu/cortexa9, arm_cortex-a9_vfpv3
- Kernel: 4.14.90
- Driver: ath10k-ct-2018-12-20-118e16da

**Problem description**
 
I'm capturing TX/RX frames while doing UL throughput tests. I've one VIF in managed mode (which is used for the test) and one VIF in monitor mode (which is used for capturing traffic sent/received by the managed mode VIF).

Captured RX frames look correct, but TX frames are missing certain information, for example:
- retry bit is never set
- QoS control data is missing (looks like all QoS Data frames that sent out are seen as ordinary Data frames in local packet capture. I've used Voice QoS for the test (6).

Locally captured frames look like below. Qos Data frames are seen as Data frames, and retry bit is never set for any frames: 
![local_capture](https://user-images.githubusercontent.com/16662378/50967727-a6ca8c80-14e1-11e9-8b0b-163df856ab06.png)

If I use an external device to take the capture, QoS TID is correct (6), and I can also see retries:

![external_capture](https://user-images.githubusercontent.com/16662378/50967760-bd70e380-14e1-11e9-8389-871fd5e24fa0.png)

Is this a limitation of ath10k driver / FW, missing feature, or a bug?

Thanks,
Jussi

**Comment by greearb** [comment]
The tx capture happens in the wifi stack before it ever gets to the driver or firmware, and you will also be missing any frames generated by the firmware itself (like retransmitted frames, ACK, blockack, etc).  This is not something that can really be fixed for any reasonable amount of effort.  Just use a second NIC as sniffer in case you need to see all of the frames exactly as they hit the air.
