### ISSUE TITLE
R7800  10.4b-ct-9984-fH-012-d6de75e0d SWBA overrun on vdev 0, skipped old beacon

### ISSUE THREAD

**Issue by schwichtgit** [greearb/ath10k-ct#65]
Description of the problem (how to configure, how to reproduce, how often it happens).
R7800 multi AP setup using 802.11r.

Software (OS, Firmware version, kernel, driver, etc)
```
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='SNAPSHOT'
DISTRIB_REVISION='r9059-6e104c63d6'
DISTRIB_TARGET='ipq806x/generic'
DISTRIB_ARCH='arm_cortex-a15_neon-vfpv4'
DISTRIB_DESCRIPTION='OpenWrt SNAPSHOT r9059-6e104c63d6'
DISTRIB_TAINTS=''
NAME="OpenWrt"
VERSION="SNAPSHOT"
ID="openwrt"
ID_LIKE="lede openwrt"
PRETTY_NAME="OpenWrt SNAPSHOT"
VERSION_ID="snapshot"
HOME_URL="http://openwrt.org/"
BUG_URL="http://bugs.openwrt.org/"
SUPPORT_URL="http://forum.lede-project.org/"
BUILD_ID="r9059-6e104c63d6"
LEDE_BOARD="ipq806x/generic"
LEDE_ARCH="arm_cortex-a15_neon-vfpv4"
LEDE_TAINTS=""
LEDE_DEVICE_MANUFACTURER="OpenWrt"
LEDE_DEVICE_MANUFACTURER_URL="http://openwrt.org/"
LEDE_DEVICE_PRODUCT="Generic"
LEDE_DEVICE_REVISION="v0"
LEDE_RELEASE="OpenWrt SNAPSHOT r9059-6e104c63d6"
```
driver: ath10k_pci
version: 4.14.93
```
wpad - 2018-12-02-c2c6c01b-1
```

Firmware: 10.4b-ct-9984-fH-012-d6de75e0d 

Hardware (NIC chipset, platform, etc)
R7800
```
0000:00:00.0 PCI bridge: Qualcomm Device 0101
0000:01:00.0 Network controller: Qualcomm Atheros QCA9984 802.11ac Wave 2 Wireless Network Adapter
0001:00:00.0 PCI bridge: Qualcomm Device 0101
0001:01:00.0 Network controller: Qualcomm Atheros QCA9984 802.11ac Wave 2 Wireless Network Adapter
```
Logs (dmesg, maybe supplicant and/or hostap)
[system-SchwichtenburgWrt.log.zip](https://github.com/greearb/ath10k-ct/files/2822378/system-SchwichtenburgWrt.log.zip)

**Comment by schwichtgit** [comment]
@greearb will you pick this one up, too ?

**Comment by greearb** [comment]
All these bugs are belong to me.  Do you see similar warnings with stock firmware?  And if not, would you like to bisect the issue if I build you an image for each of my commits?

**Comment by schwichtgit** [comment]
on

```
driver: ath10k_pci
version: 4.14.93
firmware-version: 10.4-3.9.0.2-00021
```
```
c38f8d67845d83986d347e6f7436f65b2e0323dad5911dbc96895ce575b451f2  firmware-5.bin_10.4-3.9.0.2-00021
```
I do not see a single occurrence.

however on
```
driver: ath10k_pci
version: 4.14.93
firmware-version: 10.4b-ct-9984-fH-012-d6de75e0d
```
I see
```
grep -i swba  system-SchwichtenburgWrt.log|wc -l
**915**
```

I do not mind being helpful to address this issue, as both the CT firmware and this AP R7800 are popular, so I guess many would benefit.

but the backside is, that these victim systems are in real use, so it would be good to have a focused triaging strategy to keep the pain level low on the STA users.

**Comment by greearb** [comment]
It is liable to be disruptive to users to bisect this problem.  Several other users have reported the same basic problem, so maybe one of them will step up with an offer to bisect.

**Comment by schwichtgit** [comment]
please provide the images ... I see what I can do

**Comment by greearb** [comment]
Here are images to bisect with:

https://www.candelatech.com/downloads/ath10k-9984-10-4b/ath10k-fw-beta/all_builds-9984b-H-feb-6-2019.tar.gz

**Comment by schwichtgit** [comment]
@greearb, I see a tar ball with 923 firmwares.
what is the process you suggest I should follow?

**Comment by pgera** [comment]
Binary search would be the best approach. Should take fewer than 10 tests.

**Comment by greearb** [comment]
Please see section on how to bisect toward the bottom of this page:
https://www.candelatech.com/ath10k-bugs.php

**Comment by sq-bb** [comment]
@schwichtgit Is there a specific debug level at which you see these messages, or have you been able to link them to a specific aspect of your config/network? I would be able to do the bisect, but I can't seem to reproduce the issue on my r7800 running openwrt master and firmware 10.4b-ct-9984-fH-012-5815a26a3.

**Comment by shelterx** [comment]
I saw this error too now however it doesn't seem very freqeuent for me so catching this error is next to impossible.

**Comment by shelterx** [comment]
I can only speak for myself but I haven't seen any SWBA overruns in a long time now.

**Comment by greearb** [comment]
Closing this one, hopefully it is fixed.
