### ISSUE TITLE
9980 10.4b-ct-9980-fH-012-ddc348c0 (2019.02.02) crash

### ISSUE THREAD

**Issue by notmyrealhandle** [greearb/ath10k-ct#69]
dmesg [here](https://gist.github.com/notmyrealhandle/205ac92d87e2fa8590ab7710b15f61b8)

r7500v2 running:
DISTRIB_TARGET='ipq806x/generic'
DISTRIB_ARCH='arm_cortex-a15_neon-vfpv4'
DISTRIB_DESCRIPTION='OpenWrt SNAPSHOT r9259-04fc45e352'
root@OpenWrt:~/local# uptime
 06:15:51 up 2 days, 16:10,  load average: 0.07, 0.04, 0.00

**Comment by greearb** [comment]
This is a crash in rate-ctrl.  Not the corruption thankfully, and I think I see the fix.  Please try the attached firmware.

[firmware-5-full-htt-mgt-community.bin.gz](https://github.com/greearb/ath10k-ct/files/2846427/firmware-5-full-htt-mgt-community.bin.gz)

**Comment by notmyrealhandle** [comment]
applied: 10.4b-ct-9980-fH-012-1a8f0f76

I'll report back in ~7 days or so unless issues come up or you'd like feedback sooner

**Comment by notmyrealhandle** [comment]
With respect to this bug, it looks like it went 6+ days.  Thank you.

The router reset last night - no log of what happened so nothing I can report about it.
